# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: 30 días de Streamlit
site_url: https://github.com/fralfaro/30days-spanish
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/30days-spanish
repo_url: https://github.com/fralfaro/30days-spanish
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/neoteroi-mkdocs.css

# Theme
theme:
  name: material
  language: es
  logo: images/icons/streamlit.png
  favicon: images/icons/streamlit.png
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.footer

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

#TOC
nav:
    - 🏠 Home:
        - index.md
    - 📗 Principiante: 
      - 1️⃣ Día 01: content/Day1.md
      - 2️⃣ Día 02: content/Day2.md
      - 3️⃣ Día 03: content/Day3.md
      - 4️⃣ Día 04: content/Day4.md
      - 5️⃣ Día 05: content/Day5.md
      - 6️⃣ Día 06: content/Day6.md
      - 7️⃣ Día 07: content/Day7.md
    - 📘 Intermedio: 
      - 8️⃣ Día 08: content/Day8.md
      - 9️⃣ Día 09: content/Day9.md
      - 1️⃣0️⃣ Día 10: content/Day10.md
      - 1️⃣1️⃣ Día 11: content/Day11.md
      - 1️⃣2️⃣ Día 12: content/Day12.md
      - 1️⃣3️⃣ Día 13: content/Day13.md
      - 1️⃣4️⃣ Día 14: content/Day14.md
      - 1️⃣5️⃣ Día 15: content/Day15.md
      - 1️⃣6️⃣ Día 16: content/Day16.md
      - 1️⃣7️⃣ Día 17: content/Day17.md
      - 1️⃣8️⃣ Día 18: content/Day18.md
      - 1️⃣9️⃣ Día 19: content/Day19.md
      - 2️⃣0️⃣ Día 20: content/Day20.md
      - 2️⃣1️⃣ Día 21: content/Day21.md
      - 2️⃣2️⃣ Día 22: content/Day22.md
      - 2️⃣3️⃣ Día 23: content/Day23.md
    - 📕 Avanzado: 
      - 2️⃣4️⃣ Día 24: content/Day24.md
      - 2️⃣5️⃣ Día 25: content/Day25.md
      - 2️⃣6️⃣ Día 26: content/Day26.md
      - 2️⃣7️⃣ Día 27: content/Day27.md
      - 2️⃣8️⃣ Día 28: content/Day28.md
      - 2️⃣9️⃣ Día 29: content/Day29.md 
      - 3️⃣0️⃣ Día 30: content/Day30.md